Update 1. newLinesCount.cpp
Angeld55/Object-oriented_programming_FMI pull request #51
Opened 2024-04-06 13:01 UTC by Aneliya21

2024-04-07 15:24 UTC, Angeld55 commented
tnx

2024-04-07 17:35 UTC, GeorgiTerziev02 requested changes

2024-04-07 17:35 UTC, GeorgiTerziev02 commented on Week 02/1. newLinesCount.cpp
> +	return getCharCount(ifs, NEW_LINE_CHAR);
Plus one should be here, not inside the getCharsCount function

2024-04-21 10:50 UTC, GeorgiTerziev02 approved these changes

2024-04-21 10:50 UTC, merged